### ISSUE TITLE
Stuck in Freelook.

### ISSUE THREAD

**Issue by TobezDev** [r0yzer/perspektive#12]
I have recently joined my server to find myself in freelook after installing the mod. Checked my settings and the control is set to 'y'. Upon pressing it, nothing happens. I have tried to reset it using LALT (my F5) but nothing happens. Is this something to do with the mod or is my Minecraft not working properly?

Many thanks.

(I am using Perspektive v1.2.2 with Minecraft 1.19.3 and Fabric 0.69.1+1.19.3)

**Comment by r0yzer** [comment]
hi, thats weird.
have you pressed the freelook toggle key before? if not it probably has something to do with the 1.19.3 update as i have never heared of this before

**Comment by TheRealTobes28-Codez** [comment]
Hi there.

Yes, I have tried to fiddle around with the Toggle Keybinding but that doesn't seem to do anything either. Starting to think it is something to do with 1.19.3 as it works fine on 1.16 and 1.18 versions.

**Comment by r0yzer** [comment]
as i have not made the update myself this time we will have to ask @mooziii

**Comment by TheRealTobes28-Codez** [comment]
👍 Will wait for something further to arise

**Comment by mooziii** [comment]
https://user-images.githubusercontent.com/63669478/209477761-aacd90d9-f610-4515-ba1b-eec65532e764.mp4


Works fine with fabric api 0.69.0+1.19.3, im trying it with 0.70.0+1.19.3 now.

**Comment by r0yzer** [comment]
do you have any other mods installed which might be interfering with perspektive @TheRealTobes28-Codez
