### ISSUE TITLE
Feature Request: Add Scrolling Feature for F5 as well

### ISSUE THREAD

**Issue by RisPNG** [r0yzer/perspektive#16]
It would be nice if I could also change the distance of the camera for normal third person as well and not just the freelook. Any consideration is very much appreciated. Thank you.

**Comment by r0yzer** [comment]
will do in the next update

**Comment by r0yzer** [comment]
https://modrinth.com/mod/perspektive/version/1.3.2

**Comment by RisPNG** [comment]
> https://modrinth.com/mod/perspektive/version/1.3.2

The update works but it also breaks scrolling in first person mode.

**Comment by r0yzer** [comment]
yes, forgot about that. for now just disable inventory scrolling blocking when having the third person thing enabled
![image](https://github.com/r0yzer/perspektive/assets/58533269/518ca545-232e-40da-8581-f45dd4c6bbca)

**Comment by r0yzer** [comment]
updated the version on modrinth, should work now
