### ISSUE TITLE
Feature Request: Automatically disable Freelook if on specific server (ex. Hypixel)

### ISSUE THREAD

**Issue by ItsFrocat** [r0yzer/perspektive#23]
It would also be nice if it's configurable, so you can add your own servers.

**Comment by r0yzer** [comment]
why would you need to do that

**Comment by notrohit1702** [comment]
Would be very helpful for me too!

**Comment by r0yzer** [comment]
since they can not detect it i think there is noone accidentally getting banned so im sorry but i wont be doing that haha just dont do it its not that serious

(pr still welcome)
