### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by andreasdc** [r0yzer/perspektive#5]
While being on F5 and pressing freelook, it should disable f5 too after turning off.

**Comment by r0yzer** [comment]
it is actually intended to do so, i could maybe add it as an option on the next update

**Comment by andreasdc** [comment]
> it is actually intended to do so, i could maybe add it as an option on the next update

I can't wait :)

**Comment by andreasdc** [comment]
> it is actually intended to do so, i could maybe add it as an option on the next update

You know maybe when the update will be?

**Comment by r0yzer** [comment]
maybe i´ll do it on the weekend, if not no later than the 1.19 release

**Comment by andreasdc** [comment]
> maybe i´ll do it on the weekend, if not no later than the 1.19 release

Sounds cool, it will be great option and you have great opportunity as Perspektive Mod Redux doesn't work on 1.18. 🚀

**Comment by r0yzer** [comment]
yeah, i´ll try my best

**Comment by r0yzer** [comment]
took some time but its implemented in 1.2.0
