### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mrGRINCH** [r0yzer/perspektive#9]
Would you be able to add an option to set the distance the camera is from the player?

I'd like to be able to be a bit more zoomed out for when I'm flying with an Elytra.

Either just a distance setting in the settings menu or even being able to dynamically zoom in and out with the mouse wheel.

**Comment by r0yzer** [comment]
thats a great idea, if i can figure it out it will be in the next update

**Comment by mrGRINCH** [comment]
Awesome, I look forward to it!

Is there any chance you could add me on discord, I'd like to ask you something else not regarding this mod. DMT#3607

**Comment by r0yzer** [comment]
1.2.0 is out, might add the mouse wheel thing later
